### ISSUE TITLE
Setting the culture

### ISSUE THREAD

**Issue by nacoleman** [gpeipman/AspNetCoreLocalization#1]
Hi,

I like this approach.

however I notice that this code doesn't actually set the current culture. Is it intended to do so?

    @CultureInfo.CurrentCulture.Name

Always returns 'en'

Cheers

**Comment by gpeipman** [comment]
Hi,
are you running this sample solution on .NET Core 1.x or 2.0? There are issues with 1.x but these were solved with .NET Core 2.0.
