### ISSUE TITLE
Support multiple resource files

### ISSUE THREAD

**Issue by ThunderDev1** [gpeipman/AspNetCoreLocalization#2]
Hi, thanks for this great code sample, I managed to get it up and working.

I was wondering how you would go about adding multiple resource files ?

I used generics for anyone that is interested, here is the code

```cs
public class CustomLocalizer<T> : StringLocalizer<T>

// startup.cs

services.AddTransient<CustomLocalizer<Common>>();
services.AddTransient<CustomLocalizer<Homepage>>();
services.AddTransient<CustomLocalizer<UserProfile>>();

// in view

@inject CustomLocalizer<Common> CommonLocalizer

<h1 class="text-center">@CommonLocalizer["Hello"]</h1>
```

**Comment by gpeipman** [comment]
This is one way how to do it. The other way (after applying the fix to localization pipeline I just committed) is to use resources like in previous versions of ASP.NET.

**Comment by ThunderDev1** [comment]
Thanks that's a much cleaner solution. I got it working fine, however I did come across a problem. I added the following line to use the Resources folder for my "normal" resource files.

`services.AddLocalization(options => options.ResourcesPath = "Resources");`

My shared resource file (Common) stopped working. I had to change the namespace of my shared resource files to the assembly name.
